# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jihui-event-mgr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jihui.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e68bb752d7b4ab3a40b59141ac60219 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7f808ef09034505908f5bd5f4d8026a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jihui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e68bb752d7b4ab3a40b59141ac60219 }}/jihui-event-mgr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jihui-event-mgr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0054013e63664d8890acc9607b5e51b9 }}
        images: 'jihui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e68bb752d7b4ab3a40b59141ac60219 }}/jihui-event-mgr:${{ github.sha }}'